<?php
/* Copyright (C) 2018, Logistio Limited. All Rights Reserved. */


namespace Logistio\Symmetry\Auth\Passport\Mock;


use League\OAuth2\Server\Entities\AccessTokenEntityInterface;
use League\OAuth2\Server\Entities\ClientEntityInterface;
use League\OAuth2\Server\Grant\PasswordGrant;

class MockPasswordGrant extends PasswordGrant
{

    /*
     *  tokens
        $accessToken = $passwordGrant->issueAccessToken($accessTokenTTL, $client, $userId, $finalizedScopes);
        $refreshToken = $passwordGrant->issueRefreshToken($accessToken);

     */

    /** {@inherit} */
    public function issueAccessToken(
        \DateInterval $accessTokenTTL,
        ClientEntityInterface $client,
        $userIdentifier,
        array $scopes = []
    )
    {
        // Override to make public.
        return parent::issueAccessToken($accessTokenTTL, $client, $userIdentifier, $scopes); // TODO: Change the autogenerated stub
    }

    /** {@inherit} */
    public function issueRefreshToken(AccessTokenEntityInterface $accessToken)
    {
        // Override to make public.
        return parent::issueRefreshToken($accessToken); // TODO: Change the autogenerated stub
    }


}